### ISSUE TITLE
Broken 'View test results' link in readme

### ISSUE THREAD

**Issue by hinok** [web-perf/react-perf#1]
https://axemclion.cloudant.com/react-perf/_design/site/index.html#/summary?pagename=DBMonster&browser=chrome

**Response**

```
{"error":"not_found","reason":"deleted"}
```

**Comment by axemclion** [comment]
@hinok I was jsut working on updating the results to include newer versions of react. I deleted the old table (with a backup), to run all the tests again.

Restored the database - so the links should work now.
